version: '3.9'

services:
  ton_game:
    build:
      context: .
      dockerfile: dockerfile
    deploy:
      resources:
        limits:
          memory: 512M 
          cpus: "0.5"    
    image: ton_game
    container_name: ton_game
    restart: always
    env_file:
      - .env
    ports:
      - "5696:5696"
    volumes:
      - ./public:/usr/src/app/public
